Description: |
  This is a template with some parameters to create a new vpc using
  2 public subnets and 2 private subnets, one internet gateway for
  the public subnets, and a NAT for the private networks.

Parameters:
  EnvironmentName: # enviroment name
    Description: An enviroment  name that is prefixed to resource names
    Type: String

  VpcCIDR: #define the private network to use
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 19.168.40.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
#this is another update
