AWSTemplateFormatVersion: 2010-09-09
Description: RDS PostgreSQL instance.
Parameters:
    DatabaseName:
      Default: "DBname"
      Description: The database name (Default "DBname", change if you are creating more than one database)
      Type: String
    VPC:
      Type: AWS::EC2::VPC::Id
      Description: Select a VPC to deploy
    SubnetA:
      Type: AWS::EC2::Subnet::Id
      Description: Subnet A, different from Subnet B (both public, both private)
    SubnetB:
      Type: AWS::EC2::Subnet::Id
      Description: Subnet B, different from Subment A (both public, both private)

    DatabaseInstanceType:
        Default: db.t2.micro
        AllowedValues:
            - db.t2.micro
            - db.t2.small
            - db.t2.medium
            - db.t2.large
            - db.t2.xlarge
            - db.t2.2xlarge
            - db.r4.large
            - db.r4.xlarge
            - db.r4.2xlarge
            - db.r4.4xlarge

        Description: "The instance type to use for the database."
        Type: String

    DatabasePassword:
        AllowedPattern: "[a-zA-Z0-9]+"
        ConstraintDescription: must contain only alphanumeric characters. Must have length 8-41.
        Description: The database admin account password. (Choose a secure password)
        MaxLength: '41'
        MinLength: '8'
        NoEcho: 'true'
        Type: String

    DatabaseUsername:
        Default: "biadmin"
        AllowedPattern: "[a-zA-Z0-9]+"
        ConstraintDescription: must contain only alphanumeric characters. Must have length 1-16
        Description: The database admin account user name. (Default "biadmin")
        MaxLength: '16'
        MinLength: '1'
        Type: String

    AllocatedStorage:
        Default: 20
        Description: Storage to allocate in GB (Default "20")
        Type: Number
        MinValue: 20
        MaxValue: 16384
        ConstraintDescription: Allocated storage size must be in range 20-16384 GB

Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            - Label:
                default: Database Configuration
              Parameters:
                - DatabaseInstanceType
                - DatabaseName
                - DatabaseUsername
                - DatabasePassword
        ParameterLabels:
            DatabaseName:
              default: Database name
            DatabaseInstanceType:
                default: Database Instance Type
            DatabasePassword:
                default: Database Password
            DatabaseUsername:
                default: Database Username

Resources:
    StackAlarmTopic:
        Type: AWS::SNS::Topic
        Properties:
            DisplayName: Stack Alarm Topic

    DatabaseSubnetGroup:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
            DBSubnetGroupDescription: CloudFormation managed DB subnet group.
            SubnetIds:
                - !Ref SubnetA
                - !Ref SubnetB

    ParameterGroup:
        Type: "AWS::RDS::DBParameterGroup"
        Properties:
            Description: DB parameter group
            Family: postgres11
            Parameters:
                max_connections: 300

    DatabaseInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            DBName: !Ref DatabaseName
            Engine: postgres
            EngineVersion: 11.1
            DBInstanceClass:
                Ref: DatabaseInstanceType
            DBSubnetGroupName:
                Ref: DatabaseSubnetGroup
            DBParameterGroupName: !Ref ParameterGroup
            PubliclyAccessible: "true"
            StorageType: "gp2"
            AllocatedStorage: !Ref AllocatedStorage
            BackupRetentionPeriod: 35
            DBInstanceIdentifier: !Ref DatabaseName
            MasterUsername:
              Ref: DatabaseUsername
            MasterUserPassword:
              Ref: DatabasePassword
            PreferredBackupWindow: 02:00-03:00
            PreferredMaintenanceWindow: mon:03:00-mon:04:00
            DBSubnetGroupName:
                Ref: DatabaseSubnetGroup
            VPCSecurityGroups:
                - Ref: DatabaseSecurityGroup

    DatabaseCPUAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: Primary database CPU utilization is over 80%.
            Namespace: AWS/RDS
            MetricName: CPUUtilization
            Unit: Percent
            Statistic: Average
            Period: 300
            EvaluationPeriods: 2
            Threshold: 80
            ComparisonOperator: GreaterThanOrEqualToThreshold
            Dimensions:
                - Name: DBInstanceIdentifier
                  Value:
                      Ref: DatabaseInstance
            AlarmActions:
                - Ref: StackAlarmTopic
            InsufficientDataActions:
                - Ref: StackAlarmTopic

    DatabaseMemoryAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: Primary database freeable memory is under 700MB.
            Namespace: AWS/RDS
            MetricName: FreeableMemory
            Unit: Bytes
            Statistic: Average
            Period: 300
            EvaluationPeriods: 2
            Threshold: 700000000
            ComparisonOperator: LessThanOrEqualToThreshold
            Dimensions:
                - Name: DBInstanceIdentifier
                  Value:
                      Ref: DatabaseInstance
            AlarmActions:
                - Ref: StackAlarmTopic
            InsufficientDataActions:
                - Ref: StackAlarmTopic
            OKActions:
                - Ref: StackAlarmTopic

    DatabaseSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            VpcId: !Ref VPC
            GroupDescription: Access to database
            SecurityGroupIngress:
                - CidrIp: 0.0.0.0/0
                  FromPort: 5432
                  ToPort: 5432
                  IpProtocol: tcp
            Tags:
                - Key: Name
                  Value: !Sub ${DatabaseName}-security-group

Outputs:
    DatabaseEndpoint:
        Description: The database endpointDatabaseName
        Value: !GetAtt DatabaseInstance.Endpoint.Address

    DatabasePort:
        Description: The database port
        Value: !GetAtt DatabaseInstance.Endpoint.Port

    InstanceName:
        Description: 'The name of the database instance.'
        Value: !Ref DatabaseName
